package com.somu.try_catch_finally_block;

public class ControlFlowTryCatchFinally {
	
	public static void main(String[] args) {
		
//		CASE 1 : IF THERE IS NO EXCEPTION
		
		try {
			System.out.println("Statement 1");
			System.out.println("Statement 2");
			System.out.println("Statement 3");
		} catch (ArithmeticException e) {
			System.out.println("Statement 4");
		}
		finally {
			System.out.println("Statement 5");
		}
		System.out.println("Statement 6");
		
		CASE 2 : IF THERE IS EXCEPTION AT STATEMENT 2 & CA
		
		try {
			System.out.println("Statement 1");
			System.out.println("Statement 2");
			System.out.println("Statement 3");
		} catch (ArithmeticException e) {
			System.out.println("Statement 4");
		}
		finally {
			System.out.println("Statement 5");
		}
		System.out.println("Statement 6");
		
		
		try {
			System.out.println("Statement 1");
			System.out.println("Statement 2");
			System.out.println("Statement 3");
		} catch (ArithmeticException e) {
			System.out.println("Statement 4");
		}
		finally {
			System.out.println("Statement 5");
		}
		System.out.println("Statement 6");
		
		try {
			System.out.println("Statement 1");
			System.out.println("Statement 2");
			System.out.println("Statement 3");
		} catch (ArithmeticException e) {
			System.out.println("Statement 4");
		}
		finally {
			System.out.println("Statement 5");
		}
		System.out.println("Statement 6");
		
		try {
			System.out.println("Statement 1");
			System.out.println("Statement 2");
			System.out.println("Statement 3");
		} catch (ArithmeticException e) {
			System.out.println("Statement 4");
		}
		finally {
			System.out.println("Statement 5");
		}
		System.out.println("Statement 6");
		
		try {
			System.out.println("Statement 1");
			System.out.println("Statement 2");
			System.out.println("Statement 3");
		} catch (ArithmeticException e) {
			System.out.println("Statement 4");
		}
		finally {
			System.out.println("Statement 5");
		}
		System.out.println("Statement 6");
	}
}
